# Generated by Django 4.2.1 on 2023-05-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('classification_results', models.CharField(blank=True, max_length=100, null=True)),
                ('csv_file', models.FileField(blank=True, null=True, upload_to='files/')),
                ('date_of_student', models.CharField(blank=True, max_length=100, null=True)),
                ('history_of_lecture', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
