# Generated by Django 4.2.1 on 2023-06-23 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='csv_file',
        ),
        migrations.RemoveField(
            model_name='image',
            name='date_of_student',
        ),
        migrations.RemoveField(
            model_name='image',
            name='history_of_lecture',
        ),
    ]
